CREATE DATABASE SHOPPENG;
USE SHOPPENG;

CREATE TABLE PRODUTOS(
ID_PRODUTO INT auto_increment NOT NULL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL,
QUANTIDADE INT NOT NULL,
DATA_COMPRA DATE NOT NULL
);

SELECT * FROM PRODUTOS;